SGX_SDK ?= /home/gat/intel/sgxsdk
SGX_MODE ?= HW
SGX_ARCH ?= x64
SGX_COMMON_CFLAGS := -m64

App_Name := app
Enclave_Name := enclave

SGX_SIGNER_KEY := $(SGX_SDK)/bin/private.pem

SGX_COMMON_FLAGS := -D$(SGX_MODE)
SGX_COMMON_FLAGS += -I$(SGX_SDK)/include

App_Cpp_Files := App.cpp Enclave_u.c
App_Include_Paths := -I$(SGX_SDK)/include

App_Link_Flags := -L$(SGX_SDK)/lib64 -lsgx_urts

.PHONY: all run clean

all: $(App_Name)

$(App_Name): $(App_Cpp_Files)
	@$(CXX) $(SGX_COMMON_CFLAGS) $(App_Cpp_Files) $(App_Include_Paths) $(App_Link_Flags) -o $@

run: $(App_Name)
	@./$(App_Name)

clean:
	@rm -f $(App_Name) $(Enclave_Name).signed.so $(Enclave_Name).so Enclave_u.* Enclave_t.*
